[package]
name = "fluent-syntax"
description = """
Parser/Serializer tools for Fluent Syntax. 
"""
version = "0.8.0"
edition = "2018"
authors = [
    "Zibi Braniecki <gandalf@mozilla.com>",
    "Staś Małolepszy <stas@mozilla.com>"
]
homepage = "http://www.projectfluent.org"
license = "Apache-2.0/MIT"
repository = "https://github.com/projectfluent/fluent-rs"
readme = "README.md"
keywords = ["localization", "l10n", "i18n", "intl", "internationalization"]
categories = ["localization", "internationalization"]

[dev-dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
glob = "^0.2"
assert-json-diff = "^0.2.1"
criterion = "^0.2"

[[bench]]
name = "parser"
harness = false
